# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups_amazon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ups_amazon.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10ups_amazon.proto\",\n\tAUConnect\x12\x0f\n\x07worldid\x18\x01 \x02(\x03\x12\x0e\n\x06seqnum\x18\x02 \x02(\x03\"+\n\x0bUAConnected\x12\x0f\n\x07worldid\x18\x01 \x02(\x03\x12\x0b\n\x03\x61\x63k\x18\x02 \x02(\x03\"T\n\rAUOrderDetail\x12\x12\n\nups_userid\x18\x01 \x02(\t\x12\r\n\x05pd_id\x18\x02 \x02(\x03\x12\x0e\n\x06pd_des\x18\x03 \x02(\t\x12\x10\n\x08quantity\x18\x04 \x02(\x03\"Y\n\x0b\x41UCallTruck\x12\r\n\x05\x64\x65stx\x18\r \x02(\x03\x12\r\n\x05\x64\x65sty\x18\x18 \x02(\x03\x12\r\n\x05whnum\x18# \x02(\x03\x12\x1d\n\x05order\x18\x04 \x02(\x0b\x32\x0e.AUOrderDetail\"B\n\rUATruckArrive\x12\x0f\n\x07truckid\x18\x01 \x02(\x03\x12\x11\n\tpackageid\x18\x02 \x02(\x03\x12\r\n\x05whnum\x18\x03 \x02(\x03\"c\n\x10\x41UReadyToDeliver\x12\x0f\n\x07truckid\x18\x01 \x02(\x03\x12\x11\n\tpackageid\x18\x02 \x02(\x03\x12\r\n\x05\x64\x65stx\x18\x03 \x02(\x03\x12\r\n\x05\x64\x65sty\x18\x04 \x02(\x03\x12\r\n\x05whnum\x18\x05 \x02(\x03\" \n\x0bUADelivered\x12\x11\n\tpackageid\x18\x01 \x02(\x03\"\x88\x01\n\tAUCommand\x12\x0c\n\x04type\x18\x01 \x02(\x03\x12#\n\rau_call_truck\x18\x02 \x01(\x0b\x32\x0c.AUCallTruck\x12+\n\x10\x61u_ready_deliver\x18\x03 \x01(\x0b\x32\x11.AUReadyToDeliver\x12\x0e\n\x06seqnum\x18\x04 \x02(\x03\x12\x0b\n\x03\x65rr\x18\x05 \x01(\t\"\x81\x01\n\nUAResponse\x12\x0c\n\x04type\x18\x01 \x02(\x03\x12\'\n\x0fua_truck_arrive\x18\x02 \x01(\x0b\x32\x0e.UATruckArrive\x12\"\n\x0cua_delivered\x18\x03 \x01(\x0b\x32\x0c.UADelivered\x12\x0b\n\x03\x61\x63k\x18\x04 \x02(\x03\x12\x0b\n\x03\x65rr\x18\x05 \x01(\t')
)




_AUCONNECT = _descriptor.Descriptor(
  name='AUConnect',
  full_name='AUConnect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worldid', full_name='AUConnect.worldid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='AUConnect.seqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=64,
)


_UACONNECTED = _descriptor.Descriptor(
  name='UAConnected',
  full_name='UAConnected',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worldid', full_name='UAConnected.worldid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ack', full_name='UAConnected.ack', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=109,
)


_AUORDERDETAIL = _descriptor.Descriptor(
  name='AUOrderDetail',
  full_name='AUOrderDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ups_userid', full_name='AUOrderDetail.ups_userid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pd_id', full_name='AUOrderDetail.pd_id', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pd_des', full_name='AUOrderDetail.pd_des', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='AUOrderDetail.quantity', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=195,
)


_AUCALLTRUCK = _descriptor.Descriptor(
  name='AUCallTruck',
  full_name='AUCallTruck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='destx', full_name='AUCallTruck.destx', index=0,
      number=13, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desty', full_name='AUCallTruck.desty', index=1,
      number=24, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='whnum', full_name='AUCallTruck.whnum', index=2,
      number=35, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order', full_name='AUCallTruck.order', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=286,
)


_UATRUCKARRIVE = _descriptor.Descriptor(
  name='UATruckArrive',
  full_name='UATruckArrive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='UATruckArrive.truckid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packageid', full_name='UATruckArrive.packageid', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='whnum', full_name='UATruckArrive.whnum', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=354,
)


_AUREADYTODELIVER = _descriptor.Descriptor(
  name='AUReadyToDeliver',
  full_name='AUReadyToDeliver',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='AUReadyToDeliver.truckid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packageid', full_name='AUReadyToDeliver.packageid', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destx', full_name='AUReadyToDeliver.destx', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desty', full_name='AUReadyToDeliver.desty', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='whnum', full_name='AUReadyToDeliver.whnum', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=455,
)


_UADELIVERED = _descriptor.Descriptor(
  name='UADelivered',
  full_name='UADelivered',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packageid', full_name='UADelivered.packageid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=457,
  serialized_end=489,
)


_AUCOMMAND = _descriptor.Descriptor(
  name='AUCommand',
  full_name='AUCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='AUCommand.type', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='au_call_truck', full_name='AUCommand.au_call_truck', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='au_ready_deliver', full_name='AUCommand.au_ready_deliver', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='AUCommand.seqnum', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err', full_name='AUCommand.err', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=628,
)


_UARESPONSE = _descriptor.Descriptor(
  name='UAResponse',
  full_name='UAResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UAResponse.type', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ua_truck_arrive', full_name='UAResponse.ua_truck_arrive', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ua_delivered', full_name='UAResponse.ua_delivered', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ack', full_name='UAResponse.ack', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err', full_name='UAResponse.err', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=631,
  serialized_end=760,
)

_AUCALLTRUCK.fields_by_name['order'].message_type = _AUORDERDETAIL
_AUCOMMAND.fields_by_name['au_call_truck'].message_type = _AUCALLTRUCK
_AUCOMMAND.fields_by_name['au_ready_deliver'].message_type = _AUREADYTODELIVER
_UARESPONSE.fields_by_name['ua_truck_arrive'].message_type = _UATRUCKARRIVE
_UARESPONSE.fields_by_name['ua_delivered'].message_type = _UADELIVERED
DESCRIPTOR.message_types_by_name['AUConnect'] = _AUCONNECT
DESCRIPTOR.message_types_by_name['UAConnected'] = _UACONNECTED
DESCRIPTOR.message_types_by_name['AUOrderDetail'] = _AUORDERDETAIL
DESCRIPTOR.message_types_by_name['AUCallTruck'] = _AUCALLTRUCK
DESCRIPTOR.message_types_by_name['UATruckArrive'] = _UATRUCKARRIVE
DESCRIPTOR.message_types_by_name['AUReadyToDeliver'] = _AUREADYTODELIVER
DESCRIPTOR.message_types_by_name['UADelivered'] = _UADELIVERED
DESCRIPTOR.message_types_by_name['AUCommand'] = _AUCOMMAND
DESCRIPTOR.message_types_by_name['UAResponse'] = _UARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AUConnect = _reflection.GeneratedProtocolMessageType('AUConnect', (_message.Message,), dict(
  DESCRIPTOR = _AUCONNECT,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:AUConnect)
  ))
_sym_db.RegisterMessage(AUConnect)

UAConnected = _reflection.GeneratedProtocolMessageType('UAConnected', (_message.Message,), dict(
  DESCRIPTOR = _UACONNECTED,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:UAConnected)
  ))
_sym_db.RegisterMessage(UAConnected)

AUOrderDetail = _reflection.GeneratedProtocolMessageType('AUOrderDetail', (_message.Message,), dict(
  DESCRIPTOR = _AUORDERDETAIL,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:AUOrderDetail)
  ))
_sym_db.RegisterMessage(AUOrderDetail)

AUCallTruck = _reflection.GeneratedProtocolMessageType('AUCallTruck', (_message.Message,), dict(
  DESCRIPTOR = _AUCALLTRUCK,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:AUCallTruck)
  ))
_sym_db.RegisterMessage(AUCallTruck)

UATruckArrive = _reflection.GeneratedProtocolMessageType('UATruckArrive', (_message.Message,), dict(
  DESCRIPTOR = _UATRUCKARRIVE,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:UATruckArrive)
  ))
_sym_db.RegisterMessage(UATruckArrive)

AUReadyToDeliver = _reflection.GeneratedProtocolMessageType('AUReadyToDeliver', (_message.Message,), dict(
  DESCRIPTOR = _AUREADYTODELIVER,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:AUReadyToDeliver)
  ))
_sym_db.RegisterMessage(AUReadyToDeliver)

UADelivered = _reflection.GeneratedProtocolMessageType('UADelivered', (_message.Message,), dict(
  DESCRIPTOR = _UADELIVERED,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:UADelivered)
  ))
_sym_db.RegisterMessage(UADelivered)

AUCommand = _reflection.GeneratedProtocolMessageType('AUCommand', (_message.Message,), dict(
  DESCRIPTOR = _AUCOMMAND,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:AUCommand)
  ))
_sym_db.RegisterMessage(AUCommand)

UAResponse = _reflection.GeneratedProtocolMessageType('UAResponse', (_message.Message,), dict(
  DESCRIPTOR = _UARESPONSE,
  __module__ = 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:UAResponse)
  ))
_sym_db.RegisterMessage(UAResponse)


# @@protoc_insertion_point(module_scope)
