# Generated by Django 4.2.9 on 2024-04-18 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_tmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('world_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('world_name', models.CharField(default='None', max_length=100)),
                ('active_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck_Set',
            fields=[
                ('truck_id', models.AutoField(primary_key=True, serialize=False)),
                ('truck_status', models.CharField(choices=[('I', 'IDLE'), ('A', 'ARRIVED'), ('T', 'TRAVELING'), ('L', 'LOADING'), ('D', 'DELIVERING')], default='I', max_length=1)),
                ('pos_x', models.CharField(max_length=30)),
                ('pos_y', models.CharField(max_length=30)),
                ('truck_world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myups.world')),
            ],
        ),
        migrations.CreateModel(
            name='Package_tmp',
            fields=[
                ('pkg_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('wharehouse_id', models.CharField(max_length=100)),
                ('wharehouse_x', models.CharField(max_length=30)),
                ('wharehouse_y', models.CharField(max_length=30)),
                ('dst_x', models.CharField(max_length=30)),
                ('dst_y', models.CharField(max_length=30)),
                ('pkg_status', models.CharField(choices=[('T', 'TO PICK UP'), ('LED', 'LOADED'), ('LING', 'LOADING'), ('DING', 'DELIVERING'), ('DED', 'DELIVERED')], max_length=4)),
                ('pkup_time', models.CharField(max_length=30)),
                ('ld_time', models.CharField(max_length=30)),
                ('del_time', models.CharField(max_length=30)),
                ('pkg_truck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myups.truck_set')),
                ('pkg_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myups.account_tmp')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myups.world')),
            ],
        ),
        migrations.AddField(
            model_name='account_tmp',
            name='account_world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myups.world'),
        ),
        migrations.AddField(
            model_name='account_tmp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
