# Generated by Django 5.0.4 on 2024-04-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myups', '0002_alter_package_tmp_del_time_alter_package_tmp_ld_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_tmp',
            name='pkg_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package_tmp',
            name='pkg_quant',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
